const data = [
    {
        client: 'nike',
        id: 1,
        title: 'teststride',
        backgroundColor: '#0d080f',
        backgroundFade: '#23152c',
        accentColor: '#bd0000',
        details:
            'An interactive obstacle course & immersive environment for the Nike Sneakerboots release event in Shanghai. A LiDAR tracking system triggered thematic motion graphics on a 30ft LED wall as guests competed for the fastest time.',
        year: 2016,
        type: 'Installation',
        skills: 'Concept, Code, Design, Interactive & Creative Direction',
        model: '/assets/models/nike-30k.gltf',
        media: [
            '/assets/media/nike/Nike_Course1_Left_sm.jpg',
            '<h3>Concept</h3> A brand experience that shows how Legendary Meets Necessary &mdash; merging a digital technology experience with practical physical activity. A compelling story of how Nike SneakerBoots and Tech Fleece Aeroloft are built to be used in the real world, by real people.',
            '/assets/media/nike/Nike_Course2_Right_sm.jpg',
            '/assets/media/nike/nike_villains_select_02.mp4',
            '<h3>Innovation Benefits</h3> Educate participants on product benefits that combine to fulfill SneakerBoots’ and Tech Fleece Aeroloft’s promise: Legendary Meets Necessary.',
            '/assets/media/nike/Nike_Course3_Female_Hero_sm.jpg',
            '/assets/media/nike/Nike_Course4_Leap_sm.jpg',
            '/assets/media/nike/Nike_Course6_Starting_Line_sm.jpg',
            '/assets/media/nike/nike_select_03.mp4',
            '/assets/media/nike/Nike_Event_Hallway_sm.jpg',
            '/assets/media/nike/Nike_Sneakerboots_Display_Angle_sm.jpg',
            '/assets/media/nike/Nike_Sneakerboots_Display_CU_sm.jpg',
            '/assets/media/nike/nike_villains_select_01.mp4',
            '<h3>Villains of Winter</h3> A character study of winter elements in the rawest state, up close and personal. Each shot establishes a winter element and its corresponding Nike innovation benefit. The ground generates and pulses red triangles as each element appears. These villains of winter are introduced in the legendary environment of the Nike SneakerBoots Pyramid.',
            '/assets/media/nike/Nike_Sneakerboots_Display_Wide_M_sm.jpg',
            '/assets/media/nike/Nike_TechPack1_Center_sm.jpg',
            '/assets/media/nike/Nike_TechPack2_Boots_sm.jpg',
            '/assets/media/nike/Nike_TechPack2_Vertical_sm.jpg',
        ],
        awards: [
            {
                name: 'FWA of the Day',
                icon: '/assets/images/awards/fwa.png',
                url: 'https://thefwa.com/cases/nike-test-stride',
            },
            {
                name: 'SEGD Highlight',
                icon: '/assets/images/awards/segd.png',
                url: 'https://segd.org/leviathan-demos-high-performance-nike-test-stride',
            },
            {
                name: 'Event Marketer Gold',
                icon: '/assets/images/awards/eventmarketer.png',
                url: 'http://www.eventmarketer.com/article/winners-announced-2017-experience-design-technology/',
            },
        ],
        link: { cta: 'Play Video', url: 'https://vimeo.com/194709630' },
    },
    {
        client: 'gogo',
        id: 2,
        title: '2ku',
        backgroundColor: '#0e2533',
        backgroundFade: '#106487',
        accentColor: '#25c1f3',
        details:
            'A WebGL microcosm that showcases next generation satellite technology. Explore real world flight paths as they pass through future high-speed coverage zones and learn what makes the network possible.',
        year: 2017,
        type: 'Browser Experience',
        skills: 'Concept, Code, Design, Interactive & Creative Direction',
        model: '/assets/models/gogo-60k.gltf',
        media: [
            '/assets/media/gogo/gogo-01.mp4',
            '<h3>Concept</h3> Demonstrtate that next generation 2Ku satellite technology and corresponding benefits are available now and will only increase in capability in the near future.',
            '/assets/media/gogo/gogo-02.mp4',
            '<h3>Tech</h3> Three.js and custom GLSL power a tiny planet earth complete with real world flight routes and representative satellite positioning and altitude.',
            '/assets/media/gogo/gogo-03.jpg',
            '/assets/media/gogo/gogo-03.mp4',
            '/assets/media/gogo/gogo-04.mp4',
            "<h3>Process</h3> Working directly with Gogo, careful attention was given on how to make the experience scientifically accurate, but easy enough to understand if you don't have an aerospace engineering background.",
            '/assets/media/gogo/gogo-05.mp4',
            '/assets/media/gogo/gogo-06.mp4',
            '/assets/media/gogo/gogo-02.jpg',
        ],
        awards: {},
        link: { cta: 'Play Video', url: 'https://vimeo.com/221020432' },
    },
    {
        client: 'msi',
        id: 3,
        title: 'u505',
        backgroundColor: '#002132',
        backgroundFade: '#044449',
        accentColor: '#c1893f',
        details:
            'A game that teaches visitors about the historic capture of the U-505, a WWII-era German submarine. Assuming the dive planesman role in this underwater simulation, visitors are taught how to maneuver and follow orders as they try to avoid capture, torpedoes, depth charges and the crushing depths of the open ocean.',
        year: 2016,
        type: 'Installation',
        skills: 'Code, Interactive Direction',
        model: '/assets/models/u505-30k.gltf',
        media: [
            '/assets/media/u505/u505-0.jpg',
            '<h3>Concept</h3> Educate museum visitors on the role of the diveplanes on a German U-boat and bring to life the epic underwater story of the U-505 capture.',
            '/assets/media/u505/u505-1.jpg',
            '/assets/media/u505/u505-2.jpg',
            '<h3>Installation</h3> 3 dive simulator stations each with an array of 3 HD Monitors, Physical Controls and Surround Sound augmented with physical effects.',
            '/assets/media/u505/u505-3.jpg',
            '/assets/media/u505/u505-4.jpg',
            '/assets/media/u505/u505-vfx.mp4',
            "<h3>Multiple Outcomes</h3> Follow your Captain's orders or risk capture, torpedo or depth charge attacks. Multiple storylines keep gameplay fresh and intriguing.",
            '/assets/media/u505/u505-5.jpg',
            '/assets/media/u505/u505-6.jpg',
            '/assets/media/u505/u505-dev.mp4',
            "<h3>Tech</h3> AAA quality graphics and gameplay brought to life via Unreal Engine 4. Blueprints were primarily used in development to allow 3D technical artists to collaborate who don't have a C++ background.",
            '/assets/media/u505/u505-8.jpg',
            '/assets/media/u505/u505-closing.mp4',
            '/assets/media/u505/u505-9.jpg',
        ],
        awards: {},
        link: { cta: 'Play Video', url: 'https://vimeo.com/183544570' },
    },
    {
        client: 'beyonce',
        id: 4,
        title: 'website',
        backgroundColor: '#111111',
        backgroundFade: '#393336',
        accentColor: '#d9afc9',
        details:
            'A full website for major label recording artist, Beyoncé, in advance of 2014’s On The Run World Tour.',
        year: 2014,
        type: 'Browser Experience',
        skills: 'Code, Interactive & Creative Direction',
        model: '/assets/models/beyonce-30k.gltf',
        media: [
            '/assets/media/beyonce/bey-1.jpg',
            '/assets/media/beyonce/bey-2.jpg',
            "<h3>Process</h3> I led the development team to bring Christina Rinaldi / Prima Creative's designs to life while working with Parkwood Entertainment.",
            '/assets/media/beyonce/bey-3.jpg',
            '/assets/media/beyonce/bey-4.jpg',
            '/assets/media/beyonce/bey-5.jpg',
            '/assets/media/beyonce/bey-6.gif',
        ],
        awards: {},
        link: { cta: 'Visit Beyoncé', url: 'http://www.beyonce.com/' },
    },
    {
        client: 'jordan',
        id: 5,
        title: 'xx9',
        backgroundColor: '#7ea0bb',
        backgroundFade: '#cfd3d2',
        accentColor: '#ef5200',
        details:
            'An automatic mid-air photobooth for Air Jordan XX9 release events in Chicago and New York. A tower of 8 DSLR cameras captured athletes as they took off to dunk. Onsite media playback and photo delivery via print and MMS.',
        year: 2014,
        type: 'Installation',
        skills: 'Concept, Code, Design, Hardware',
        model: '/assets/models/jumpman-30k.gltf',
        media: [
            '/assets/media/jordan/jordan-0.jpg',
            '/assets/media/jordan/jordan-1.jpg',
            '/assets/media/jordan/jordan-2.jpg',
            '/assets/media/jordan/jordan-3.jpg',
            '/assets/media/jordan/jordan-4.jpg',
            '/assets/media/jordan/jordan-5.jpg',
            '/assets/media/jordan/jordan-6.jpg',
        ],
        awards: {},
        link: { cta: 'OFFLINE', url: '' },
    },
];
